# 모든 리소스를 구성하는 매우 간단하면서도 강력한 쿠버네티스 기능
# 리소스에 첨부하는 임의의 키/값 쌍 (app: test)
# 레이블 셀렉터를 사용하면 각종 리소스를 필터링하여 선택할 수 있음
# 리소스는 한 개 이상의 레이블을 가질 수 있음
# 리소스를 만드는 시점에 레이블을 첨부
# 기존 리소스에도 레이블의 값을 수정 및 추가 가능
# 모든 사람이 이해할 수 있는 체계적인 시스템을 구축 가능

# 새로운 레이블 추가
# $ kubectl label pod http-go-v2 test-foo

# 기존의 레이블을 수정할 떄
# $ kubectl label pod http-go-v2 rel=beta --overwrite

# 레이블 삭제
# $ kubectl label pod http-go-v2 rel-

# 레이블 보여주기
# $ kubectl get pod --show-labels

# 특정 레이블 칼럼으로 확인
# $ kubectl get pod -L app,rel

# 레이블 필터링하여 검색
# $ kubectl get pod --show-labels -l 'env'
# $ kubectl get pod --show-labels -l '!env'
# $ kubectl get pod --show-labels -l 'env!=test'
# $ kubectl get pod --show-labels -l 'env!=test,rel=beta'

apiVersion: v1
kind: Pod
metadata:
    name: nodejs-manual-v3
    labels:
        creation_method: manual-v3
spec:
    containers:
        - name: http-go
          image: gasbugs/http-go
          ports:
              - containerPort: 8008
                protocol: TCP
