apiVersion: v1
kind: Pod
metadata:
    name: nginx-redis-pod
spec:
    containers:
        - name: nginx
          image: busybox
          ports:
              - containerPort: 80
        - name: redis
          image: redis
